### ISSUE TITLE
OpenUPM 업데이트 에러

### ISSUE THREAD

**Issue by sr4dev** [seonghwan-dev/AssetLens#43]
**Describe the bug**
OpenUPM에서 0.3.2 버전 업데이트에 실패한 듯 싶습니다.

**To Reproduce**
https://openupm.com/packages/com.calci.assetlens/?subPage=pipelines

**Expected behavior**
0.3.2 버전의 배포.

**Screenshots**
![image](https://user-images.githubusercontent.com/9159336/140679138-1f9bf436-5076-44fd-b0f9-1b93b166fcc5.png)

**Additional context**
자꾸 번거로운 이슈를 추가해서 죄송합니다 ㅠㅠ
급하게 대응해주실 필요는 없으니 여유되실 때 확인해주시는 것만으로도 감사합니다.....!

**Comment by seonghwan-dev** [comment]
음... OpenUPM 파이프라인이 익숙치가 않아 기존에는 자동으로 업데이트 되는 방식으로 두었는데, 프로젝트 구조를 변경하면서 이제 CLI나 액션으로 따로 관리를 해 주어야 할 것 같습니다. 차차 살펴보고 다음 버전에는 npm 버전처럼 Actions 를 이용하여 자동화 하는 등 방법을 고려해보겠습니다. 혹여나 관련하여 아시는 방법이나 정보가 있으시다면 도움을 주시는건 대 환영입니다 :D

**Comment by sr4dev** [comment]
확인 감사합니다.

UPM 업데이트는 저도 JSON만 수정하면 자동으로 업데이트되는 것에 의존하고 있습니다 ㅠ
가끔 JSON 수정을 까먹고 그냥 커밋해버리는 때가 있는데, 그럴 땐 태그를 하나 더 끊어서 버전을 올린 뒤 자동으로 돌아가도록 하고 있네요;

UPM으로 0.3.1 설치시 컴파일 에러는 발생해도 패키지 다운로드와 설치는 문제 없이 작동했습니다!

**Comment by seonghwan-dev** [comment]
방금 확인해보니 upm/0.3.2 태그가 등록이 된 것 처럼 보이는데 동작하는지 확인 부탁드립니다.
이 파이프라인이 작동하면 이대로 유지하도록 하겠습니다.

**Comment by sr4dev** [comment]
UPM에서 0.3.2로 업데이트에 성공했습니다! 전에 발생했던 컴파일 에러도 해결된 것을 확인했습니다!
조속환 확인과 대응에 감사드립니다 ㅠㅠㅠ!!!
